<?php

namespace Alyosha\Core;

interface ModuleInterface
{
    /**
     * @return array
     * Return the names of the events the module is listening to
     */
    public function getTriggers();

    /**
     * Execute warm-up of the module, like connections to database or similar
     */
    public function fire();

    /**
     * @return array
     * Return events generated by the module.
     */
    public function getEvents();

    /**
     * @param Event $event
     * Notify the module of an event. This might create another event which will
     * be collected by the method getEvents.
     */
    public function notify(Event $event);

    /**
     * @return string
     * Return module name, mostly for debug
     */
    public function getName();
}

